### ISSUE TITLE
MuteNewGuilds breaks DMs

### ISSUE THREAD

**Issue by MicrocontrollersDev** [attic0001/enmityaddons#6]
The plug-in makes all DMs say the server is muted. Changing the mute status of the dm itself does not fix this, and as far as I can tell there doesn’t seem to be a way to fix it in Discord. It would be great if the plugins had an option to unmute all servers a user is in to fix this in the meanwhile as this has affected every single DM I have. Thanks.

**Comment by attic0001** [comment]
What enmity version are you using?

**Comment by MicrocontrollersDev** [comment]
happened on enmity 2.1.4 for discord 147

**Comment by MicrocontrollersDev** [comment]
Got on my alt and figured out how I managed to do this. Using the [FriendInvites](https://github.com/spinfal/enmity-plugins/tree/master/FriendInvites) enmity plugin.

Steps:
1. Get on an alt and make a friend invite using the plugin
2. Switch back to main and accept invite
3. Click on the "Send a Message" button
4. Long press the DM and go to Notification Settings to see that the "server" is muted

**Comment by MicrocontrollersDev** [comment]
Thanks for the fix, any chance we’ll see a way to revert broken DMs?

**Comment by attic0001** [comment]
haven't exactly looked at that yet. will take a look tomorrow or sunday.
